### ISSUE TITLE
Inconsistent stringWidth() within Kravur.hx

### ISSUE THREAD

**Issue by CoruNethron** [Kode/Kha#723]
Hello. In getCharWidth() we expect to receive character index or character code?

```
	private function getCharWidth(charIndex: Int): Float {
		if (charIndex < 32) return 0;
		if (charIndex - 32 >= chars.length) return 0;
		return chars[charIndex - 32].xadvance;
	}

	public function stringWidth(string: String): Float {
		var str = new SuperString(string);
		var width: Float = 0;
		for (c in 0...str.length) {
			width += getCharWidth(str.charCodeAt(c));
		}
		return width;
	}
```

If we pass, for example, next string: "QWERЙЦУК", that contains some Latin and some Cyrillic characters, then Cyrillic part will be ignored, because character codes will be: [81, 87, 69, 82, 1049, 1062, 1059, 1050]

As result, I have an inconsistent render in Zui library:
![screenshot_3](https://user-images.githubusercontent.com/4215824/34647439-8cb4fbf8-f3ce-11e7-9d7e-7e1b697a7fe3.png)
Some characters are out of borders, center alignment unable to work correctly etc.

----

This issue happened because I'm trying to add Cyrillic characters to the myFontGlyphs collection within graphics2/Graphics.hx constructor, like this:

```
		for (i in 32...256) myFontGlyphs.push(i);
		for(i in 1040...1104) myFontGlyphs.push(i);
		myFontGlyphs.push(1025);
		myFontGlyphs.push(1105);
```

**Comment by RblSb** [comment]
Oh, we fixed it recently :) Please update Kha and test again
https://github.com/Kode/Kha/blob/master/Sources/kha/Kravur.hx#L86

**Comment by RobDangerous** [comment]
Well, I guess that works, please reopen if some issues remain.
